server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/socialnet
    username: root
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    open-in-view: false
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

auth:
  secret: someSecretCode
  time-to-live: 3600000000